on:
  push:
    branches: [master]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: org.gustavoperedo.FontDownloader
        manifest-path: org.gustavoperedo.FontDownloader.Master.json
        cache-key: flatpak-builder-${{ github.sha }}
